apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: azsoq0ndr-nodejs 
  janus-idp.io/tekton: azsoq0ndr-nodejs
  backstage.io/kubernetes-id: azsoq0ndr-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: azsoq0ndr-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml