apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: azsoq0ndr-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: azsoq0ndr-nodejs 
  name: azsoq0ndr-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: azsoq0ndr-nodejs 
